#!/bin/bash
# Interactive .env setup for AI-Recruiter
# Run: bash setup-env.sh

set -e

echo ""
echo "========================================"
echo "  AI-Recruiter — Environment Setup"
echo "========================================"
echo ""

# ── Secrets ──────────────────────────────────────────────────────────────────
echo "--- SECRETS ---"
echo ""

read -rp "ADMIN_API_TOKEN (press Enter to auto-generate): " ADMIN_API_TOKEN
if [ -z "$ADMIN_API_TOKEN" ]; then
    ADMIN_API_TOKEN=$(openssl rand -hex 32)
    echo "  Generated: $ADMIN_API_TOKEN"
fi

read -rp "INTERVIEW_LINK_SECRET (press Enter to auto-generate): " INTERVIEW_LINK_SECRET
if [ -z "$INTERVIEW_LINK_SECRET" ]; then
    INTERVIEW_LINK_SECRET=$(openssl rand -hex 32)
    echo "  Generated: $INTERVIEW_LINK_SECRET"
fi

read -rp "IQ_TEST_SECRET (press Enter to auto-generate): " IQ_TEST_SECRET
if [ -z "$IQ_TEST_SECRET" ]; then
    IQ_TEST_SECRET=$(openssl rand -hex 32)
    echo "  Generated: $IQ_TEST_SECRET"
fi

echo ""

# ── Database ─────────────────────────────────────────────────────────────────
echo "--- DATABASE ---"
echo ""

read -rp "DB_USER [ai_user]: " DB_USER
DB_USER=${DB_USER:-ai_user}

read -rsp "DB_PASSWORD [secure_password]: " DB_PASSWORD
echo ""
DB_PASSWORD=${DB_PASSWORD:-secure_password}

read -rp "DB_NAME [ai_recruiter]: " DB_NAME
DB_NAME=${DB_NAME:-ai_recruiter}

echo ""

# ── HR Login ─────────────────────────────────────────────────────────────────
echo "--- HR DASHBOARD LOGIN ---"
echo ""

read -rp "ADMIN_EMAIL: " ADMIN_EMAIL
read -rsp "ADMIN_PASSWORD: " ADMIN_PASSWORD
echo ""

read -rp "HR_EMAIL (optional, leave blank to skip): " HR_EMAIL
if [ -n "$HR_EMAIL" ]; then
    read -rsp "HR_PASSWORD: " HR_PASSWORD
    echo ""
else
    HR_PASSWORD=""
fi

echo ""

# ── URLs ─────────────────────────────────────────────────────────────────────
echo "--- URLS ---"
echo ""

read -rp "Your domain or public IP (e.g. careers.example.com or 44.231.40.162): " HOST
HOST=${HOST:-localhost}

# Detect if it looks like an IP or domain
if [[ "$HOST" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    WEB_BASE_URL="http://$HOST"
    NEXT_PUBLIC_VOICE_URL="http://$HOST/voice"
    CORS_ALLOW_ORIGINS="http://$HOST,http://$HOST:3000"
else
    WEB_BASE_URL="https://$HOST"
    NEXT_PUBLIC_VOICE_URL="https://$HOST/voice"
    CORS_ALLOW_ORIGINS="https://$HOST,http://$HOST"
fi

echo "  WEB_BASE_URL:          $WEB_BASE_URL"
echo "  NEXT_PUBLIC_VOICE_URL: $NEXT_PUBLIC_VOICE_URL"
echo "  CORS_ALLOW_ORIGINS:    $CORS_ALLOW_ORIGINS"
echo ""

# ── API Keys ─────────────────────────────────────────────────────────────────
echo "--- API KEYS ---"
echo ""

read -rp "GROQ_API_KEY: " GROQ_API_KEY
read -rp "GROQ_MODEL [llama-3.3-70b-versatile]: " GROQ_MODEL
GROQ_MODEL=${GROQ_MODEL:-llama-3.3-70b-versatile}

read -rp "DEEPGRAM_API_KEY: " DEEPGRAM_API_KEY
read -rp "CARTESIA_API_KEY: " CARTESIA_API_KEY
read -rp "CARTESIA_VOICE_ID [71a7ad14-091c-4e8e-a314-022ece01c121]: " CARTESIA_VOICE_ID
CARTESIA_VOICE_ID=${CARTESIA_VOICE_ID:-71a7ad14-091c-4e8e-a314-022ece01c121}

read -rp "OPENAI_API_KEY (optional, press Enter to skip): " OPENAI_API_KEY

echo ""

# ── LiveKit ───────────────────────────────────────────────────────────────────
echo "--- LIVEKIT (voice interviews) ---"
echo ""

read -rp "LIVEKIT_URL (e.g. wss://your-project.livekit.cloud): " LIVEKIT_URL
read -rp "LIVEKIT_API_KEY: " LIVEKIT_API_KEY
read -rsp "LIVEKIT_API_SECRET: " LIVEKIT_API_SECRET
echo ""

echo ""

# ── Email ─────────────────────────────────────────────────────────────────────
echo "--- SMTP EMAIL (optional — for interview invite emails) ---"
echo ""

read -rp "SMTP_EMAIL (leave blank to skip): " SMTP_EMAIL
if [ -n "$SMTP_EMAIL" ]; then
    read -rsp "SMTP_PASSWORD: " SMTP_PASSWORD
    echo ""
    read -rp "SMTP_HOST [smtp.gmail.com]: " SMTP_HOST
    SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
    read -rp "SMTP_PORT [587]: " SMTP_PORT
    SMTP_PORT=${SMTP_PORT:-587}
else
    SMTP_PASSWORD=""
    SMTP_HOST=""
    SMTP_PORT=""
fi

echo ""

# ── Voice features ────────────────────────────────────────────────────────────
echo "--- VOICE FEATURES ---"
echo ""

read -rp "BILINGUAL_MODE (true/false) [true]: " BILINGUAL_MODE
BILINGUAL_MODE=${BILINGUAL_MODE:-true}

read -rp "NOISE_CANCELLATION (true/false) [true]: " NOISE_CANCELLATION
NOISE_CANCELLATION=${NOISE_CANCELLATION:-true}

# ── Detect if running over HTTP (no domain) ───────────────────────────────────
if [[ "$HOST" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    COOKIE_SECURE=false
else
    COOKIE_SECURE=true
fi

# ── Write .env ────────────────────────────────────────────────────────────────
cat > .env <<EOF
# Generated by setup-env.sh

# --- Secrets ---
ADMIN_API_TOKEN=$ADMIN_API_TOKEN
INTERVIEW_LINK_SECRET=$INTERVIEW_LINK_SECRET
IQ_TEST_SECRET=$IQ_TEST_SECRET

# --- Database ---
DB_USER=$DB_USER
DB_PASSWORD=$DB_PASSWORD
DB_NAME=$DB_NAME
DATABASE_URL=postgresql+psycopg2://$DB_USER:$DB_PASSWORD@postgres:5432/$DB_NAME

# --- HR Dashboard Login ---
ADMIN_EMAIL=$ADMIN_EMAIL
ADMIN_PASSWORD=$ADMIN_PASSWORD
HR_EMAIL=$HR_EMAIL
HR_PASSWORD=$HR_PASSWORD

# --- URLs ---
WEB_BASE_URL=$WEB_BASE_URL
NEXT_PUBLIC_VOICE_URL=$NEXT_PUBLIC_VOICE_URL
CORS_ALLOW_ORIGINS=$CORS_ALLOW_ORIGINS

# --- API Keys ---
GROQ_API_KEY=$GROQ_API_KEY
GROQ_MODEL=$GROQ_MODEL
DEEPGRAM_API_KEY=$DEEPGRAM_API_KEY
CARTESIA_API_KEY=$CARTESIA_API_KEY
CARTESIA_VOICE_ID=$CARTESIA_VOICE_ID
OPENAI_API_KEY=$OPENAI_API_KEY

# --- LiveKit ---
LIVEKIT_URL=$LIVEKIT_URL
LIVEKIT_API_KEY=$LIVEKIT_API_KEY
LIVEKIT_API_SECRET=$LIVEKIT_API_SECRET

# --- Email (SMTP) ---
SMTP_EMAIL=$SMTP_EMAIL
SMTP_PASSWORD=$SMTP_PASSWORD
SMTP_HOST=$SMTP_HOST
SMTP_PORT=$SMTP_PORT

# --- Voice Features ---
BILINGUAL_MODE=$BILINGUAL_MODE
NOISE_CANCELLATION=$NOISE_CANCELLATION
START_DEFAULT_BOT=false

# --- Cookie security (set to true when HTTPS is enabled) ---
COOKIE_SECURE=$COOKIE_SECURE

# --- Recordings ---
RECORDINGS_DIR=/data/recordings
EOF

echo "========================================"
echo "  .env written successfully!"
echo "========================================"
echo ""
echo "Next steps:"
echo "  docker compose up --build -d"
echo ""
