#!/usr/bin/env python3
"""Drive a MOCK interview against a running runner.py — no mic, browser, or WebRTC.

Posts scripted candidate answers to the bot's POST /chat endpoint (the same text
path the dashboard chat box uses) and prints the agent's live replies as they come
back over the /events SSE stream. The agent text is generated by the real LLM; in a
live call the TTS would speak exactly these lines, so this is a fast, deterministic
way to exercise the full interview conversation flow.

Prereqs: runner.py is up (default :7860).  Run it (NOT bot.py):
    cd voice-agent/server && uv run runner.py

Usage:
    uv run python scripts/mock_interview.py                 # built-in sample answers
    uv run python scripts/mock_interview.py --file answers.json   # answers = ["...", "..."]
    uv run python scripts/mock_interview.py --session <id> --delay 8

`--session <id>` targets a specific candidate interview; omit it to drive the
default dashboard bot. For full VOICE fidelity (synthesize each agent line via
Cartesia, or feed answers through STT) see the notes at the bottom of this file.
"""
import argparse
import json
import sys
import threading
import time
import urllib.request
from pathlib import Path

SAMPLE_ANSWERS = [
    "Hi, I'm ready to begin the interview.",
    "Recently I debugged a production memory leak in our Node service. I profiled "
    "heap snapshots, found event listeners that were never removed, fixed the "
    "cleanup, and cut memory growth by about 80 percent.",
    "When the team disagrees I focus on the shared goal. On an API design dispute I "
    "set up a short meeting, let each side explain their reasoning, and we agreed on "
    "a compromise interface — the conflict was resolved without lingering tension.",
]


def _post_chat(url: str, text: str, session: str | None) -> dict:
    payload = {"text": text}
    if session:
        payload["session"] = session
    req = urllib.request.Request(
        f"{url}/chat",
        data=json.dumps(payload).encode(),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.loads(resp.read())


def _stream_events(url: str, stop: threading.Event):
    """Print agent turns from the SSE /events stream until stop is set."""
    try:
        with urllib.request.urlopen(f"{url}/events", timeout=300) as resp:
            for raw in resp:
                if stop.is_set():
                    return
                line = raw.decode(errors="replace").strip()
                if not line.startswith("data:"):
                    continue
                try:
                    evt = json.loads(line[len("data:"):].strip())
                except ValueError:
                    continue
                if evt.get("speaker") == "agent" and evt.get("text"):
                    print(f"\n  🤖 AGENT: {evt['text'].strip()}\n")
    except Exception as e:  # noqa: BLE001 - listener is best-effort
        if not stop.is_set():
            print(f"[events stream closed: {e}]", file=sys.stderr)


def main():
    ap = argparse.ArgumentParser(description="Run a scripted mock interview over /chat.")
    ap.add_argument("--url", default="http://127.0.0.1:7860", help="runner.py base URL")
    ap.add_argument("--file", help="JSON file: a list of candidate answer strings")
    ap.add_argument("--session", help="target a specific interview session_id")
    ap.add_argument("--delay", type=float, default=8.0, help="seconds between turns (LLM needs time)")
    args = ap.parse_args()

    answers = SAMPLE_ANSWERS
    if args.file:
        answers = json.loads(Path(args.file).read_text())
        if not isinstance(answers, list):
            sys.exit("--file must contain a JSON list of answer strings")

    stop = threading.Event()
    listener = threading.Thread(target=_stream_events, args=(args.url, stop), daemon=True)
    listener.start()
    time.sleep(1.5)  # let the SSE stream connect before the first turn

    print(f"== Mock interview against {args.url} (session={args.session or 'default'}) ==")
    for i, text in enumerate(answers, 1):
        print(f"  🧑 CANDIDATE [{i}/{len(answers)}]: {text}")
        try:
            res = _post_chat(args.url, text, args.session)
        except Exception as e:  # noqa: BLE001
            sys.exit(f"POST /chat failed — is runner.py up at {args.url}? ({e})")
        if res.get("error"):
            sys.exit(f"runner rejected the turn: {res['error']}")
        time.sleep(args.delay)  # wait for the agent to think + reply on the stream

    time.sleep(2)
    stop.set()
    print("== done ==")


if __name__ == "__main__":
    main()

# ── Full-voice fidelity (optional) ──────────────────────────────────────────────
# This driver uses the text path. To exercise STT/TTS too:
#   • TTS-only check: synthesize each agent line with Cartesia (CARTESIA_API_KEY is
#     already configured) to hear/inspect the spoken output.
#   • End-to-end voice: publish TTS audio of each ANSWER as the candidate participant
#     into the LiveKit room (or a virtual mic) so it flows mic→Deepgram STT→LLM→TTS.
#     That needs a LiveKit publisher / virtual audio device — heavier, but it's the
#     only way to also cover the STT leg.
