#!/usr/bin/env python3
"""Drive a MOCK interview against a running runner.py — no mic, browser, or WebRTC.

Posts scripted candidate answers to the bot's POST /chat endpoint (the same text
path the dashboard chat box uses) and prints the agent's live replies from the
/events SSE stream. The agent text is generated by the real LLM; in a live call the
TTS speaks exactly these lines.

Pacing is TURN-AWARE (not a blind fixed delay): after each candidate answer it waits
for the interviewer's reply on the SSE stream, then pauses long enough for the spoken
reply to finish (estimated from the reply length) before sending the next answer — so
the conversation flows smoothly instead of talking over itself.

Prereqs: runner.py is up (default :7860).  Run it (NOT bot.py):
    cd voice-agent/server && uv run runner.py

Usage:
    uv run python scripts/mock_interview.py                        # built-in short answers
    uv run python scripts/mock_interview.py --file answers.json    # answers = ["...", "..."]
    uv run python scripts/mock_interview.py --session <id>         # target a live interview
"""
import argparse
import json
import sys
import threading
import time
import urllib.request
from pathlib import Path

# Short, natural candidate answers (1–2 sentences each) for a Data Scientist mock.
# Long answers made the exchange drag and talk over the interviewer's voice, so each
# is concise. A longer list = a longer interview (the interviewer keeps asking).
SAMPLE_ANSWERS = [
    "Hi! Yes, I'm ready to start.",
    "Most recently I built a churn-prediction model that lifted retention by about 8%.",
    "I started with gradient-boosted trees as a strong baseline, then compared it against "
    "logistic regression for interpretability.",
    "For missing values I look at why they're missing first, then use median or model-based "
    "imputation depending on the feature.",
    "I guard against overfitting with cross-validation, regularization, and watching the "
    "gap between train and validation scores.",
    "I pick the metric from the business goal — for churn I optimized recall and PR-AUC, "
    "since false negatives cost us the most.",
    "Before shipping, I run an A/B test and monitor for data drift so the model doesn't "
    "silently degrade in production.",
    "When the team disagrees, I focus on the shared goal — each side explains their "
    "reasoning, then we pick what best serves the user.",
    "I'd measure success by real user impact, not just offline metrics — did the change "
    "actually make their decisions easier?",
    "Something I'm proud of: I mentored two juniors who now run their own model pipelines.",
]

WORDS_PER_SEC = 2.7  # rough TTS speaking rate, for estimating when the voice finishes


def _post_chat(url: str, text: str, session: str | None) -> dict:
    payload = {"text": text}
    if session:
        payload["session"] = session
    req = urllib.request.Request(
        f"{url}/chat",
        data=json.dumps(payload).encode(),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.loads(resp.read())


class AgentReplies:
    """Collects interviewer turns from the SSE stream so the driver can wait on them."""
    def __init__(self):
        self._lock = threading.Lock()
        self._new = threading.Event()
        self.last_text = ""

    def add(self, text: str):
        with self._lock:
            self.last_text = text
            self._new.set()

    def wait_for_reply(self, timeout: float) -> str | None:
        """Block until the next agent turn arrives (or timeout). Returns its text."""
        self._new.clear()
        if self._new.wait(timeout):
            with self._lock:
                return self.last_text
        return None


def _stream_events(url: str, replies: AgentReplies, stop: threading.Event):
    try:
        with urllib.request.urlopen(f"{url}/events", timeout=300) as resp:
            for raw in resp:
                if stop.is_set():
                    return
                line = raw.decode(errors="replace").strip()
                if not line.startswith("data:"):
                    continue
                try:
                    evt = json.loads(line[len("data:"):].strip())
                except ValueError:
                    continue
                if evt.get("speaker") == "agent" and evt.get("text"):
                    text = evt["text"].strip()
                    print(f"\n  🤖 INTERVIEWER: {text}\n")
                    replies.add(text)
    except Exception as e:  # noqa: BLE001 - listener is best-effort
        if not stop.is_set():
            print(f"[events stream closed: {e}]", file=sys.stderr)


def _speech_seconds(text: str) -> float:
    """How long the interviewer's reply will take to speak — so we don't cut it off."""
    words = max(1, len(text.split()))
    return min(20.0, words / WORDS_PER_SEC + 1.5)  # + lead/tail, capped


def main():
    ap = argparse.ArgumentParser(description="Run a scripted, turn-aware mock interview over /chat.")
    ap.add_argument("--url", default="http://127.0.0.1:7860", help="runner.py base URL")
    ap.add_argument("--file", help="JSON file: a list of candidate answer strings")
    ap.add_argument("--session", help="target a specific interview session_id")
    ap.add_argument("--reply-timeout", type=float, default=25.0,
                    help="max seconds to wait for each interviewer reply")
    ap.add_argument("--no-end", action="store_true",
                    help="don't auto-end/finalize the session when the script finishes")
    args = ap.parse_args()

    answers = SAMPLE_ANSWERS
    if args.file:
        answers = json.loads(Path(args.file).read_text())
        if not isinstance(answers, list):
            sys.exit("--file must contain a JSON list of answer strings")

    replies = AgentReplies()
    stop = threading.Event()
    listener = threading.Thread(target=_stream_events, args=(args.url, replies, stop), daemon=True)
    listener.start()
    time.sleep(1.5)  # let the SSE stream connect before the first turn

    print(f"== Mock interview against {args.url} (session={args.session or 'default'}) ==")
    for i, text in enumerate(answers, 1):
        print(f"  🧑 CANDIDATE [{i}/{len(answers)}]: {text}")
        try:
            res = _post_chat(args.url, text, args.session)
        except Exception as e:  # noqa: BLE001
            sys.exit(f"POST /chat failed — is runner.py up at {args.url}? ({e})")
        if res.get("error"):
            sys.exit(f"runner rejected the turn: {res['error']}")

        # Wait for the interviewer's reply, then let its spoken audio finish before the
        # next answer — this is what makes the exchange smooth rather than overlapping.
        reply = replies.wait_for_reply(args.reply_timeout)
        if reply:
            time.sleep(_speech_seconds(reply))
        else:
            print("  …(no interviewer reply yet; continuing)")
            time.sleep(2)

    time.sleep(1)
    # End the interview so it finalizes NOW — saving the recording and running the
    # post-call evaluation — instead of waiting for the idle timeout. Without this the
    # HR panel shows nothing until the session times out (~10 min).
    if args.session and not args.no_end:
        try:
            req = urllib.request.Request(
                f"{args.url}/interview/end",
                data=json.dumps({"session": args.session}).encode(),
                headers={"Content-Type": "application/json"},
                method="POST",
            )
            with urllib.request.urlopen(req, timeout=15) as resp:
                res = json.loads(resp.read())
            print(f"== finalizing interview ({res.get('status') or res.get('error')}) — "
                  f"recording + evaluation will appear in the HR panel shortly ==")
        except Exception as e:  # noqa: BLE001
            print(f"[could not auto-end the interview: {e}]", file=sys.stderr)

    stop.set()
    print("== done ==")


if __name__ == "__main__":
    main()

# ── Full-voice fidelity (optional) ──────────────────────────────────────────────
# This driver uses the text path; the interviewer is voiced by the bot's TTS. To also
# voice the CANDIDATE / exercise STT, publish TTS audio of each answer as the candidate
# participant into the LiveKit room (or a virtual mic) — heavier, needs a LiveKit publisher.
