import type { Candidate, Job } from './types';

export const jobs: Job[] = [
  {
    id: 'job-001',
    title: 'Senior Frontend Engineer',
    department: 'Engineering',
    description: 'Lead the development of our next-gen analytics platform using React, TypeScript, and WebGL. Mentor junior engineers and drive architecture decisions.',
    llmPrompt: 'Evaluate candidates on React 19 patterns, TypeScript proficiency, performance optimization, and system design. Probe for experience with real-time data visualization and accessibility standards.',
    candidateCount: 12,
    status: 'Active',
    scoreDistribution: [1, 2, 4, 3, 2],
    avgScore: 68,
    createdAt: '2025-01-14',
  },
  {
    id: 'job-002',
    title: 'Product Designer',
    department: 'Design',
    description: 'Own the end-to-end design lifecycle for our mobile and web products. Collaborate closely with PM and engineering to ship delightful experiences.',
    llmPrompt: 'Assess portfolio depth, design systems thinking, prototyping skills, and user research methodology. Look for strong visual craft and the ability to articulate design rationale.',
    candidateCount: 8,
    status: 'Active',
    scoreDistribution: [0, 1, 3, 3, 1],
    avgScore: 71,
    createdAt: '2025-01-20',
  },
  {
    id: 'job-003',
    title: 'Machine Learning Engineer',
    department: 'AI & Data',
    description: 'Build and deploy production ML models at scale. Work on recommendation systems, NLP pipelines, and real-time inference infrastructure.',
    llmPrompt: 'Probe deep learning fundamentals, MLOps maturity, model deployment experience, and production monitoring. Evaluate familiarity with transformers, vector databases, and distributed training.',
    candidateCount: 15,
    status: 'Active',
    scoreDistribution: [2, 3, 5, 4, 1],
    avgScore: 58,
    createdAt: '2025-02-02',
  },
  {
    id: 'job-004',
    title: 'DevOps Engineer',
    department: 'Infrastructure',
    description: 'Automate our cloud infrastructure, build CI/CD pipelines, and ensure 99.99 percent uptime across multi-region deployments.',
    llmPrompt: 'Evaluate Kubernetes expertise, infrastructure-as-code, observability stack familiarity, and incident response maturity. Probe for cost optimization and security best practices.',
    candidateCount: 6,
    status: 'Active',
    scoreDistribution: [0, 1, 2, 2, 1],
    avgScore: 74,
    createdAt: '2025-02-10',
  },
  {
    id: 'job-005',
    title: 'Backend Engineer (Legacy)',
    department: 'Engineering',
    description: 'Maintain and modernize our legacy billing microservices. Gradual migration from monolith to event-driven architecture.',
    llmPrompt: 'Assess Java/Spring proficiency, database optimization, and refactoring strategy. Probe for experience with strangler-fig pattern and zero-downtime migrations.',
    candidateCount: 4,
    status: 'Archived',
    scoreDistribution: [1, 2, 1, 0, 0],
    avgScore: 41,
    createdAt: '2024-11-03',
  },
  {
    id: 'job-006',
    title: 'Growth Marketing Manager',
    department: 'Marketing',
    description: 'Drive user acquisition and retention through data-informed growth experiments. Own the funnel from impression to activation.',
    llmPrompt: 'Evaluate growth-loop fluency, experimentation rigor, analytics tooling depth, and cross-functional leadership. Probe for CAC/LTV modeling and viral mechanics understanding.',
    candidateCount: 9,
    status: 'Active',
    scoreDistribution: [1, 1, 3, 3, 2],
    avgScore: 66,
    createdAt: '2025-02-18',
  },
];

export const candidates: Candidate[] = [
  {
    id: 'cand-001',
    name: 'Amara Okafor',
    jobTitle: 'Senior Frontend Engineer',
    jobId: 'job-001',
    score: 88,
    status: 'Shortlisted',
    appliedDate: '2025-02-14',
    avatarColor: '#1C99BF',
    decision: 'HIRE',
    summary: { profileMatch: 92, semanticMatch: 85, llmScore: 90, aiMatch: 89 },
    interview: {
      duration: '24:18',
      talkRatio: 42,
      goalsCovered: 7,
      totalGoals: 8,
      engagementAvg: 8.4,
      strengths: [
        'Deep React 19 expertise — explained concurrent rendering and Suspense boundaries with clarity',
        'Strong TypeScript discipline — demonstrated discriminated unions and exhaustive type narrowing',
        'Excellent system design instincts — proposed a sensible WebGL pipeline for real-time charts',
        'Mentorship mindset — articulated a concrete code-review rubric for junior engineers',
      ],
      developmentAreas: [
        'Could strengthen knowledge of WebGPU compute shaders',
        'Accessibility testing workflow could be more systematic',
      ],
      botTalkRatio: 58,
      candidateTalkRatio: 42,
      engagementTimeline: [7, 8, 8, 9, 9, 8, 9, 8, 9, 9, 8, 8],
      miniStats: [
        { label: 'Presence', value: '98%' },
        { label: 'Engagement', value: '8.4/10' },
        { label: 'Frames Captured', value: '1,248' },
      ],
      assessmentScores: [
        { label: 'React Patterns', score: 94 },
        { label: 'TypeScript', score: 90 },
        { label: 'System Design', score: 88 },
        { label: 'Performance', score: 85 },
        { label: 'Accessibility', score: 78 },
        { label: 'Testing', score: 82 },
        { label: 'Code Quality', score: 91 },
      ],
      goals: [
        { title: 'React 19 concurrent rendering', coverage: 100, outcome: 'Passed' },
        { title: 'TypeScript type system', coverage: 96, outcome: 'Passed' },
        { title: 'WebGL data pipeline', coverage: 88, outcome: 'Passed' },
        { title: 'Mentorship approach', coverage: 100, outcome: 'Passed' },
        { title: 'Performance budgeting', coverage: 85, outcome: 'Passed' },
        { title: 'WebGPU shaders', coverage: 40, outcome: 'Failed' },
        { title: 'a11y testing', coverage: 65, outcome: 'Partial' },
        { title: 'Code review rubric', coverage: 100, outcome: 'Passed' },
      ],
      transcript: [
        { speaker: 'bot', text: 'Welcome, Amara. To start, could you walk me through how you would architect a real-time analytics dashboard rendering 50,000 data points at 60fps?', time: '00:12' },
        { speaker: 'candidate', text: 'Absolutely. I would reach for WebGL first — a points-based renderer with a level-of-detail strategy. For the React layer, I would use Suspense boundaries to keep the UI responsive while the GPU buffer uploads.', time: '00:34' },
        { speaker: 'bot', text: 'Good. How would you handle type safety for the shader uniform contracts?', time: '01:20' },
        { speaker: 'candidate', text: 'I would use a discriminated union for each uniform type, with a narrow function per variant. That way the TypeScript compiler catches mismatches at build time.', time: '01:48' },
        { speaker: 'bot', text: 'How do you mentor a junior engineer who keeps introducing implicit any types?', time: '03:10' },
        { speaker: 'candidate', text: 'I maintain a shared code-review rubric. The first item is always type safety. I would pair with them for one sprint, then gradually let them own reviews with me as a reviewer.', time: '03:42' },
        { speaker: 'bot', text: 'Tell me about a time you had to optimize a slow React tree.', time: '05:30' },
        { speaker: 'candidate', text: 'We had a list re-rendering on every keystroke. I introduced a memoized row component, moved the filter logic into a selector, and used useDeferredValue for the search input. Frame time dropped from 40ms to 6ms.', time: '05:58' },
        { speaker: 'bot', text: 'Last question — how would you test for WCAG compliance in that dashboard?', time: '08:40' },
        { speaker: 'candidate', text: 'I combine axe-core in the CI pipeline with manual screen-reader passes. I would like to make the automated layer more systematic — that is an area I am actively improving.', time: '09:05' },
      ],
    },
  },
  {
    id: 'cand-002',
    name: 'Dmitri Volkov',
    jobTitle: 'Machine Learning Engineer',
    jobId: 'job-003',
    score: 79,
    status: 'In Interview',
    appliedDate: '2025-02-16',
    avatarColor: '#F5B544',
    decision: 'HIRE',
    summary: { profileMatch: 81, semanticMatch: 76, llmScore: 82, aiMatch: 80 },
    interview: {
      duration: '22:04',
      talkRatio: 45,
      goalsCovered: 6,
      totalGoals: 8,
      engagementAvg: 7.9,
      strengths: [
        'Strong transformer architecture knowledge — explained attention scaling clearly',
        'Solid MLOps experience — described a model registry with staged rollouts',
        'Pragmatic on cost — proposed distillation to cut inference spend by 40 percent',
      ],
      developmentAreas: [
        'Vector database selection reasoning was a bit shallow',
        'Could improve on distributed training monitoring',
      ],
      botTalkRatio: 55,
      candidateTalkRatio: 45,
      engagementTimeline: [7, 8, 7, 8, 8, 9, 7, 8, 8, 7, 8, 7],
      miniStats: [
        { label: 'Presence', value: '96%' },
        { label: 'Engagement', value: '7.9/10' },
        { label: 'Frames Captured', value: '1,102' },
      ],
      assessmentScores: [
        { label: 'Deep Learning', score: 88 },
        { label: 'MLOps', score: 84 },
        { label: 'NLP', score: 82 },
        { label: 'PyTorch', score: 86 },
        { label: 'Deployment', score: 80 },
        { label: 'Distributed', score: 72 },
        { label: 'Cost Optimize', score: 78 },
      ],
      goals: [
        { title: 'Transformer internals', coverage: 95, outcome: 'Passed' },
        { title: 'Model registry design', coverage: 90, outcome: 'Passed' },
        { title: 'Inference cost', coverage: 88, outcome: 'Passed' },
        { title: 'NLP pipeline', coverage: 82, outcome: 'Passed' },
        { title: 'Vector DB selection', coverage: 55, outcome: 'Partial' },
        { title: 'Distributed training', coverage: 50, outcome: 'Partial' },
        { title: 'Monitoring', coverage: 60, outcome: 'Partial' },
        { title: 'RAG architecture', coverage: 78, outcome: 'Passed' },
      ],
      transcript: [
        { speaker: 'bot', text: 'Hello Dmitri. Can you explain how you would scale a transformer model for a million-document retrieval workload?', time: '00:10' },
        { speaker: 'candidate', text: 'Sure. I would use a cross-encoder for re-ranking and a bi-encoder for retrieval. To scale, I would shard the index and add a quantized ANN layer.', time: '00:35' },
        { speaker: 'bot', text: 'How do you monitor a distributed training job across 8 GPUs?', time: '02:15' },
        { speaker: 'candidate', text: 'I track gradient norms per replica and use NCCL all-reduce timing as a health signal. I have not yet built a full dashboard for it — that is something I want to improve.', time: '02:44' },
      ],
    },
  },
  {
    id: 'cand-003',
    name: 'Priya Nair',
    jobTitle: 'Product Designer',
    jobId: 'job-002',
    score: 91,
    status: 'Shortlisted',
    appliedDate: '2025-02-18',
    avatarColor: '#34C28A',
    decision: 'HIRE',
    summary: { profileMatch: 94, semanticMatch: 88, llmScore: 93, aiMatch: 92 },
    interview: {
      duration: '26:40',
      talkRatio: 48,
      goalsCovered: 8,
      totalGoals: 8,
      engagementAvg: 9.1,
      strengths: [
        'Exceptional design-systems thinking — built a token architecture with semantic aliases',
        'Strong prototyping — demonstrated a Figma-to-code variable sync workflow',
        'User research rigor — described a diary study that reshaped an onboarding flow',
        'Clear rationale — articulated every decision against a measurable user outcome',
      ],
      developmentAreas: [
        'Could explore motion design more deeply',
      ],
      botTalkRatio: 52,
      candidateTalkRatio: 48,
      engagementTimeline: [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
      miniStats: [
        { label: 'Presence', value: '100%' },
        { label: 'Engagement', value: '9.1/10' },
        { label: 'Frames Captured', value: '1,540' },
      ],
      assessmentScores: [
        { label: 'Design Systems', score: 96 },
        { label: 'Prototyping', score: 92 },
        { label: 'User Research', score: 94 },
        { label: 'Visual Craft', score: 90 },
        { label: 'Figma', score: 95 },
        { label: 'Motion', score: 78 },
        { label: 'Rationale', score: 93 },
      ],
      goals: [
        { title: 'Token architecture', coverage: 100, outcome: 'Passed' },
        { title: 'Variable sync', coverage: 96, outcome: 'Passed' },
        { title: 'Diary study', coverage: 100, outcome: 'Passed' },
        { title: 'Onboarding redesign', coverage: 100, outcome: 'Passed' },
        { title: 'Component API', coverage: 95, outcome: 'Passed' },
        { title: 'Accessibility audit', coverage: 92, outcome: 'Passed' },
        { title: 'Motion design', coverage: 70, outcome: 'Partial' },
        { title: 'Design rationale', coverage: 100, outcome: 'Passed' },
      ],
      transcript: [
        { speaker: 'bot', text: 'Welcome Priya. Walk me through how you would structure a design token system for a multi-brand product.', time: '00:08' },
        { speaker: 'candidate', text: 'I start with primitive tokens — raw color and spacing values — then build semantic aliases like surface-strong and surface-weak. Each brand maps only to the semantic layer, so a theme switch is a one-file change.', time: '00:30' },
      ],
    },
  },
  {
    id: 'cand-004',
    name: 'Marcus Chen',
    jobTitle: 'DevOps Engineer',
    jobId: 'job-004',
    score: 72,
    status: 'Pending Review',
    appliedDate: '2025-02-20',
    avatarColor: '#1C99BF',
    decision: 'CONSIDER',
    summary: { profileMatch: 70, semanticMatch: 74, llmScore: 71, aiMatch: 72 },
    interview: {
      duration: '20:12',
      talkRatio: 38,
      goalsCovered: 5,
      totalGoals: 8,
      engagementAvg: 7.2,
      strengths: [
        'Solid Kubernetes experience — described a blue-green deploy on EKS',
        'Good observability instincts — proposed SLO-based alerting',
      ],
      developmentAreas: [
        'Terraform module composition could be cleaner',
        'Security posture reasoning was surface-level',
        'Cost optimization ideas were limited',
      ],
      botTalkRatio: 62,
      candidateTalkRatio: 38,
      engagementTimeline: [7, 7, 8, 7, 7, 6, 7, 7, 8, 7, 7, 7],
      miniStats: [
        { label: 'Presence', value: '94%' },
        { label: 'Engagement', value: '7.2/10' },
        { label: 'Frames Captured', value: '980' },
      ],
      assessmentScores: [
        { label: 'Kubernetes', score: 82 },
        { label: 'Terraform', score: 68 },
        { label: 'CI/CD', score: 78 },
        { label: 'Observability', score: 80 },
        { label: 'Security', score: 65 },
        { label: 'AWS', score: 76 },
        { label: 'Cost Opt', score: 60 },
      ],
      goals: [
        { title: 'Blue-green deploy', coverage: 88, outcome: 'Passed' },
        { title: 'SLO alerting', coverage: 82, outcome: 'Passed' },
        { title: 'Terraform modules', coverage: 55, outcome: 'Partial' },
        { title: 'Security posture', coverage: 50, outcome: 'Partial' },
        { title: 'Cost optimization', coverage: 40, outcome: 'Failed' },
        { title: 'Incident response', coverage: 70, outcome: 'Partial' },
        { title: 'Multi-region', coverage: 65, outcome: 'Partial' },
        { title: 'IaC patterns', coverage: 60, outcome: 'Partial' },
      ],
      transcript: [
        { speaker: 'bot', text: 'Hi Marcus. How would you architect a zero-downtime deploy for a stateful service on Kubernetes?', time: '00:10' },
        { speaker: 'candidate', text: 'I would use a blue-green strategy with two deployments and a service switch. For stateful, I would ensure PVC migration is staged first.', time: '00:32' },
      ],
    },
  },
  {
    id: 'cand-005',
    name: 'Sofia Reyes',
    jobTitle: 'Growth Marketing Manager',
    jobId: 'job-006',
    score: 64,
    status: 'Pending Review',
    appliedDate: '2025-02-22',
    avatarColor: '#F5B544',
    decision: 'CONSIDER',
    summary: { profileMatch: 60, semanticMatch: 66, llmScore: 65, aiMatch: 64 },
    interview: {
      duration: '18:50',
      talkRatio: 40,
      goalsCovered: 4,
      totalGoals: 8,
      engagementAvg: 6.8,
      strengths: [
        'Good experimentation framework — described a holdout test design',
        'Decent analytics tooling familiarity',
      ],
      developmentAreas: [
        'CAC/LTV modeling was imprecise',
        'Viral mechanics understanding was thin',
        'Cross-functional leadership examples were vague',
      ],
      botTalkRatio: 60,
      candidateTalkRatio: 40,
      engagementTimeline: [6, 7, 7, 6, 7, 6, 7, 6, 7, 7, 6, 6],
      miniStats: [
        { label: 'Presence', value: '92%' },
        { label: 'Engagement', value: '6.8/10' },
        { label: 'Frames Captured', value: '870' },
      ],
      assessmentScores: [
        { label: 'Growth Loops', score: 70 },
        { label: 'Experimentation', score: 74 },
        { label: 'Analytics', score: 68 },
        { label: 'CAC/LTV', score: 58 },
        { label: 'Viral Mech', score: 55 },
        { label: 'Leadership', score: 62 },
        { label: 'Copywriting', score: 66 },
      ],
      goals: [
        { title: 'Holdout test', coverage: 78, outcome: 'Passed' },
        { title: 'Funnel mapping', coverage: 65, outcome: 'Partial' },
        { title: 'CAC modeling', coverage: 50, outcome: 'Partial' },
        { title: 'Viral loop', coverage: 40, outcome: 'Failed' },
        { title: 'Retention', coverage: 60, outcome: 'Partial' },
        { title: 'Activation', coverage: 55, outcome: 'Partial' },
        { title: 'Leadership', coverage: 50, outcome: 'Partial' },
        { title: 'Brand', coverage: 65, outcome: 'Partial' },
      ],
      transcript: [
        { speaker: 'bot', text: 'Hello Sofia. Describe a growth experiment you ran and its outcome.', time: '00:09' },
        { speaker: 'candidate', text: 'We tested a referral incentive. I set up a holdout group and measured 30-day retention. The lift was 12 percent and we rolled it out.', time: '00:28' },
      ],
    },
  },
  {
    id: 'cand-006',
    name: 'Liam OBrien',
    jobTitle: 'Senior Frontend Engineer',
    jobId: 'job-001',
    score: 41,
    status: 'Rejected',
    appliedDate: '2025-02-10',
    avatarColor: '#F25C7C',
    decision: 'REJECT',
    summary: { profileMatch: 38, semanticMatch: 44, llmScore: 40, aiMatch: 41 },
    interview: {
      duration: '14:20',
      talkRatio: 30,
      goalsCovered: 2,
      totalGoals: 8,
      engagementAvg: 4.2,
      strengths: [
        'Basic React component knowledge',
      ],
      developmentAreas: [
        'TypeScript type narrowing was weak',
        'No system design depth',
        'Performance optimization ideas were absent',
        'Could not explain Suspense or concurrent rendering',
      ],
      botTalkRatio: 70,
      candidateTalkRatio: 30,
      engagementTimeline: [4, 5, 4, 4, 5, 4, 5, 4, 4, 5, 4, 4],
      miniStats: [
        { label: 'Presence', value: '88%' },
        { label: 'Engagement', value: '4.2/10' },
        { label: 'Frames Captured', value: '620' },
      ],
      assessmentScores: [
        { label: 'React Patterns', score: 45 },
        { label: 'TypeScript', score: 38 },
        { label: 'System Design', score: 30 },
        { label: 'Performance', score: 35 },
        { label: 'Accessibility', score: 40 },
        { label: 'Testing', score: 42 },
        { label: 'Code Quality', score: 48 },
      ],
      goals: [
        { title: 'React 19 rendering', coverage: 30, outcome: 'Failed' },
        { title: 'TypeScript types', coverage: 25, outcome: 'Failed' },
        { title: 'WebGL pipeline', coverage: 10, outcome: 'Failed' },
        { title: 'Mentorship', coverage: 40, outcome: 'Failed' },
        { title: 'Performance', coverage: 20, outcome: 'Failed' },
        { title: 'WebGPU', coverage: 5, outcome: 'Failed' },
        { title: 'a11y', coverage: 30, outcome: 'Failed' },
        { title: 'Code review', coverage: 35, outcome: 'Failed' },
      ],
      transcript: [
        { speaker: 'bot', text: 'Hi Liam. Can you explain how Suspense works in React 19?', time: '00:08' },
        { speaker: 'candidate', text: 'I have not really used it. I mostly write class components.', time: '00:20' },
      ],
    },
  },
  {
    id: 'cand-007',
    name: 'Yuki Tanaka',
    jobTitle: 'Machine Learning Engineer',
    jobId: 'job-003',
    score: 55,
    status: 'Pending Review',
    appliedDate: '2025-02-24',
    avatarColor: '#F5B544',
    decision: 'CONSIDER',
    summary: { profileMatch: 52, semanticMatch: 58, llmScore: 54, aiMatch: 55 },
    interview: {
      duration: '19:30',
      talkRatio: 42,
      goalsCovered: 4,
      totalGoals: 8,
      engagementAvg: 6.5,
      strengths: [
        'Decent PyTorch fundamentals',
        'Reasonable NLP pipeline understanding',
      ],
      developmentAreas: [
        'MLOps maturity is low',
        'Deployment monitoring was thin',
      ],
      botTalkRatio: 58,
      candidateTalkRatio: 42,
      engagementTimeline: [6, 7, 6, 7, 6, 7, 6, 7, 6, 7, 6, 6],
      miniStats: [
        { label: 'Presence', value: '90%' },
        { label: 'Engagement', value: '6.5/10' },
        { label: 'Frames Captured', value: '810' },
      ],
      assessmentScores: [
        { label: 'Deep Learning', score: 62 },
        { label: 'MLOps', score: 50 },
        { label: 'NLP', score: 65 },
        { label: 'PyTorch', score: 60 },
        { label: 'Deployment', score: 48 },
        { label: 'Distributed', score: 42 },
        { label: 'Cost Optimize', score: 52 },
      ],
      goals: [
        { title: 'Transformer', coverage: 60, outcome: 'Partial' },
        { title: 'Model registry', coverage: 50, outcome: 'Partial' },
        { title: 'Inference cost', coverage: 45, outcome: 'Partial' },
        { title: 'NLP pipeline', coverage: 65, outcome: 'Partial' },
        { title: 'Vector DB', coverage: 40, outcome: 'Failed' },
        { title: 'Distributed', coverage: 35, outcome: 'Failed' },
        { title: 'Monitoring', coverage: 42, outcome: 'Partial' },
        { title: 'RAG', coverage: 55, outcome: 'Partial' },
      ],
      transcript: [
        { speaker: 'bot', text: 'Hi Yuki. Explain how you would deploy a BERT model for real-time inference.', time: '00:09' },
        { speaker: 'candidate', text: 'I would use TorchServe with a batched handler. For monitoring, I track latency percentiles.', time: '00:25' },
      ],
    },
  },
  {
    id: 'cand-008',
    name: 'Elena Petrova',
    jobTitle: 'Product Designer',
    jobId: 'job-002',
    score: 38,
    status: 'Rejected',
    appliedDate: '2025-02-08',
    avatarColor: '#F25C7C',
    decision: 'REJECT',
    summary: { profileMatch: 35, semanticMatch: 40, llmScore: 36, aiMatch: 38 },
    interview: {
      duration: '12:15',
      talkRatio: 28,
      goalsCovered: 2,
      totalGoals: 8,
      engagementAvg: 3.8,
      strengths: [
        'Basic Figma proficiency',
      ],
      developmentAreas: [
        'No design-systems thinking',
        'User research was absent',
        'Visual craft was weak',
        'Could not articulate design rationale',
      ],
      botTalkRatio: 72,
      candidateTalkRatio: 28,
      engagementTimeline: [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 3],
      miniStats: [
        { label: 'Presence', value: '85%' },
        { label: 'Engagement', value: '3.8/10' },
        { label: 'Frames Captured', value: '540' },
      ],
      assessmentScores: [
        { label: 'Design Systems', score: 30 },
        { label: 'Prototyping', score: 40 },
        { label: 'User Research', score: 25 },
        { label: 'Visual Craft', score: 35 },
        { label: 'Figma', score: 45 },
        { label: 'Motion', score: 28 },
        { label: 'Rationale', score: 32 },
      ],
      goals: [
        { title: 'Token system', coverage: 20, outcome: 'Failed' },
        { title: 'Variable sync', coverage: 15, outcome: 'Failed' },
        { title: 'Diary study', coverage: 10, outcome: 'Failed' },
        { title: 'Onboarding', coverage: 25, outcome: 'Failed' },
        { title: 'Component API', coverage: 20, outcome: 'Failed' },
        { title: 'a11y audit', coverage: 15, outcome: 'Failed' },
        { title: 'Motion', coverage: 18, outcome: 'Failed' },
        { title: 'Rationale', coverage: 22, outcome: 'Failed' },
      ],
      transcript: [
        { speaker: 'bot', text: 'Hi Elena. How do you approach building a design system?', time: '00:08' },
        { speaker: 'candidate', text: 'I just use the default Figma components mostly.', time: '00:15' },
      ],
    },
  },
  {
    id: 'cand-009',
    name: 'Kwame Mensah',
    jobTitle: 'DevOps Engineer',
    jobId: 'job-004',
    score: 82,
    status: 'Shortlisted',
    appliedDate: '2025-02-26',
    avatarColor: '#34C28A',
    decision: 'HIRE',
    summary: { profileMatch: 80, semanticMatch: 84, llmScore: 83, aiMatch: 82 },
    interview: {
      duration: '23:45',
      talkRatio: 46,
      goalsCovered: 7,
      totalGoals: 8,
      engagementAvg: 8.1,
      strengths: [
        'Excellent Terraform module design — showed a composable module graph',
        'Strong security posture — described a zero-trust network model',
        'Good cost optimization — proposed savings plans and spot scheduling',
      ],
      developmentAreas: [
        'Could deepen multi-region failover automation',
      ],
      botTalkRatio: 54,
      candidateTalkRatio: 46,
      engagementTimeline: [8, 8, 9, 8, 8, 9, 8, 8, 9, 8, 8, 8],
      miniStats: [
        { label: 'Presence', value: '97%' },
        { label: 'Engagement', value: '8.1/10' },
        { label: 'Frames Captured', value: '1,180' },
      ],
      assessmentScores: [
        { label: 'Kubernetes', score: 88 },
        { label: 'Terraform', score: 90 },
        { label: 'CI/CD', score: 85 },
        { label: 'Observability', score: 82 },
        { label: 'Security', score: 86 },
        { label: 'AWS', score: 84 },
        { label: 'Cost Opt', score: 80 },
      ],
      goals: [
        { title: 'Module graph', coverage: 95, outcome: 'Passed' },
        { title: 'Zero-trust', coverage: 92, outcome: 'Passed' },
        { title: 'Savings plans', coverage: 88, outcome: 'Passed' },
        { title: 'Spot scheduling', coverage: 85, outcome: 'Passed' },
        { title: 'Failover', coverage: 65, outcome: 'Partial' },
        { title: 'Incident', coverage: 80, outcome: 'Passed' },
        { title: 'Multi-region', coverage: 70, outcome: 'Partial' },
        { title: 'IaC', coverage: 88, outcome: 'Passed' },
      ],
      transcript: [
        { speaker: 'bot', text: 'Hi Kwame. How do you compose Terraform modules for a multi-environment setup?', time: '00:10' },
        { speaker: 'candidate', text: 'I build a base module with variables, then wrap it with environment-specific modules that set the variable values. Each environment is a separate state file.', time: '00:32' },
      ],
    },
  },
  {
    id: 'cand-010',
    name: 'Aisha Khan',
    jobTitle: 'Growth Marketing Manager',
    jobId: 'job-006',
    score: 76,
    status: 'In Interview',
    appliedDate: '2025-02-28',
    avatarColor: '#1C99BF',
    decision: 'HIRE',
    summary: { profileMatch: 74, semanticMatch: 78, llmScore: 77, aiMatch: 76 },
    interview: {
      duration: '21:30',
      talkRatio: 44,
      goalsCovered: 6,
      totalGoals: 8,
      engagementAvg: 7.8,
      strengths: [
        'Strong growth-loop fluency — described a content-to-community loop',
        'Rigorous experimentation — showed a sequential testing framework',
        'Good CAC/LTV modeling — broke down unit economics by channel',
      ],
      developmentAreas: [
        'Viral mechanics could be deeper',
      ],
      botTalkRatio: 56,
      candidateTalkRatio: 44,
      engagementTimeline: [7, 8, 8, 8, 7, 8, 8, 8, 7, 8, 8, 7],
      miniStats: [
        { label: 'Presence', value: '95%' },
        { label: 'Engagement', value: '7.8/10' },
        { label: 'Frames Captured', value: '1,090' },
      ],
      assessmentScores: [
        { label: 'Growth Loops', score: 82 },
        { label: 'Experimentation', score: 85 },
        { label: 'Analytics', score: 78 },
        { label: 'CAC/LTV', score: 80 },
        { label: 'Viral Mech', score: 68 },
        { label: 'Leadership', score: 75 },
        { label: 'Copywriting', score: 72 },
      ],
      goals: [
        { title: 'Content loop', coverage: 88, outcome: 'Passed' },
        { title: 'Sequential test', coverage: 90, outcome: 'Passed' },
        { title: 'Unit economics', coverage: 85, outcome: 'Passed' },
        { title: 'Channel mix', coverage: 80, outcome: 'Passed' },
        { title: 'Viral loop', coverage: 55, outcome: 'Partial' },
        { title: 'Retention', coverage: 75, outcome: 'Passed' },
        { title: 'Activation', coverage: 78, outcome: 'Passed' },
        { title: 'Leadership', coverage: 70, outcome: 'Partial' },
      ],
      transcript: [
        { speaker: 'bot', text: 'Hi Aisha. Describe a growth loop you have built.', time: '00:09' },
        { speaker: 'candidate', text: 'We built a content-to-community loop. Each article drives signups, who join a community, which produces more content. The loop compounds at 1.4x per cycle.', time: '00:28' },
      ],
    },
  },
];
